# Sales Order to TimescaleDB (Classic / Kubernetes)
# For UMH Core, see: ../flows/sales_order_to_timescale.yaml

input:
  kafka_franz:
    seed_brokers:
      - united-manufacturing-hub-kafka.united-manufacturing-hub.svc.cluster.local:9092
    topics:
      - umh.v1.*._sales_order.create
      - umh.v1.*._sales_order.update
    regexp_topics: true
    consumer_group: sales_order_to_timescale
    client_id: sales_order_to_timescale

pipeline:
  processors:
    - bloblang: |
        let kafka_key = meta("kafka_key")
        root = if $kafka_key == "create" || $kafka_key == "update" { this } else { deleted() }

output:
  sql_raw:
    driver: postgres
    dsn: postgres://kafkatopostgresqlv2:changemetoo@united-manufacturing-hub.united-manufacturing-hub.svc.cluster.local:5432/umh_v2
    query: |
      WITH upserted AS (
        INSERT INTO erp_sales_order (
          order_id, asset_id, customer_name, milestone,
          due_date, order_date, delivered_date, status, change_type
        )
        VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
        ON CONFLICT (order_id, asset_id) DO UPDATE SET
          customer_name = EXCLUDED.customer_name,
          milestone = EXCLUDED.milestone,
          due_date = EXCLUDED.due_date,
          order_date = EXCLUDED.order_date,
          delivered_date = EXCLUDED.delivered_date,
          status = EXCLUDED.status,
          change_type = EXCLUDED.change_type
        RETURNING *
      )
      INSERT INTO erp_sales_order_history (
        order_id, asset_id, customer_name, milestone,
        due_date, order_date, delivered_date, status, change_type
      )
      SELECT order_id, asset_id, customer_name, milestone,
             due_date, order_date, delivered_date, status, change_type
      FROM upserted;
    args_mapping: |
      [
        this.order_id,
        this.asset_id,
        this.customer_name,
        this.milestone,
        this.due_date,
        this.order_date,
        this.delivered_date,
        this.status,
        meta("kafka_key").uppercase()
      ]
    max_in_flight: 512
